### ISSUE TITLE
[23년 4월 3주차] 그래프 탐색

### ISSUE THREAD

**Issue by ParkJungYoon** [studying-ice-bear/pparkkkimeom#1]
## 🚀 스터디

전설의 시작... 다시 돌아왔다.. 코딩몬스터

- `일시`: 2023-04-17 (월) 20시 ~ 21시 30분 (1.5h)
- `참석자`
  - [x] 유진, 정윤, 보선
- `내용`
   -  1시간 동안 문제 설명
     -  어떤 문제를 설명할지는 랜덤으로 결정
   - 30분 동안 라이브 코테

### 🧩 과제
- 스터디 전까지 풀이한 뒤 커밋해주세요.
- 문제 풀이 결과를 댓글에 알려주세요!! 
  -  ex. 대단하다 나 자신. 이걸 풀어? 하... 인구 이동 문제 풀이 완!

|          순번           |        문제 번호         |        문제 이름         |         난이도          | 
| :-----: | :-----: | :-----: | :-----: |
| 01 | <a href="https://www.acmicpc.net/problem/16918" target="_blank">16918</a> | <a href="https://www.acmicpc.net/problem/16918" target="_blank">봄버맨</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/10.svg"/> |
| 02  | <a href="https://www.acmicpc.net/problem/4179" target="_blank">4179</a> | <a href="https://www.acmicpc.net/problem/4179" target="_blank">불!</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/12.svg"/> 
| 03  | <a href="https://www.acmicpc.net/problem/16234" target="_blank">16234</a> | <a href="https://www.acmicpc.net/problem/16234" target="_blank">인구 이동</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/11.svg"/>

**Comment by ParkJungYoon** [comment]
### 04.14 (금) : 인구 이동

- 풀이 완료!! 나보다 시간 빠른 사람 나오면 가만안둬... 다시 풀러 갈거니깐 다들 공유해주세요.

![스크린샷 2023-04-14 오후 11 11 15](https://user-images.githubusercontent.com/97580782/232068632-674aafe7-7c40-4ecb-afcf-dcea64f73d33.png)

**Comment by ParkJungYoon** [comment]
### 04.15 (토) : 봄버맨
- 어우.. 둘 다 시간복잡도 머선 일이지
![스크린샷 2023-04-15 오후 9 29 48](https://user-images.githubusercontent.com/97580782/232223648-3f8388dd-9108-4f5d-bd53-44dde7397ce0.png)

**Comment by elizabethgim** [comment]
### 04.15.(토)
- 풀어봤던 문제인데 쉽지 않아..
![image](https://user-images.githubusercontent.com/65852282/232224312-01fe47fe-0558-47a5-8eca-70b1a1c5e78e.png)

**Comment by bedurgi999** [comment]
04.16 (일) : 봄버맨
![image](https://user-images.githubusercontent.com/55628887/232302517-1a46b1fb-68f7-4e09-b342-49b897f51c4a.png)

**Comment by bedurgi999** [comment]
### **04.16 (일) : 불!**
![image](https://user-images.githubusercontent.com/55628887/232302587-a4d64fbf-b560-46fa-a3f5-0ded6103294c.png)

**Comment by bedurgi999** [comment]
### **04.16 (일) : 인구 이동**
![image](https://user-images.githubusercontent.com/55628887/232302660-33f140dc-9409-4a63-988b-332bc7f7ea0a.png)

**Comment by ParkJungYoon** [comment]
## 라이브코딩

### 04.17(월)
|          순번           |        문제 번호         |        문제 이름         |         난이도          | 
| :-----: | :-----: | :-----: | :-----: |
| 02 | <a href="https://www.acmicpc.net/problem/11725" target="_blank">11725</a> | <a href="https://www.acmicpc.net/problem/11725" target="_blank">트리의 부모 찾기</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/9.svg"/>

**Comment by elizabethgim** [comment]
![image](https://user-images.githubusercontent.com/65852282/232488879-389e6b38-3da7-484d-bce7-22d2ffdca691.png)
