### ISSUE TITLE
[23년 4월 4주차] 동적계획법 1

### ISSUE THREAD

**Issue by ParkJungYoon** [studying-ice-bear/pparkkkimeom#2]
## 🚀 스터디

전설의 시작... 다시 돌아왔다.. 코딩몬스터

- `일시`: 2023-04-26 (수) 20시 ~ 21시 30분 (1.5h)
- `참석자`
  - [x] 유진, 정윤, 보선, 채정
- `내용`
   -  1시간 동안 문제 설명
     -  어떤 문제를 설명할지는 랜덤으로 결정
   - 30분 동안 라이브 코테

### 🧩 과제
- 저번 주차 못푼 과제를 완료해주세요!
- 스터디 전까지 풀이한 뒤 커밋해주세요.
- 문제 풀이 결과를 댓글에 알려주세요!! 
  -  ex. 대단하다 나 자신. 이걸 풀어? 하... 인구 이동 문제 풀이 완!

|          순번           |        문제 번호         |        문제 이름         |         난이도          | 
| :-----: | :-----: | :-----: | :-----: |
| 01  | <a href="https://www.acmicpc.net/problem/9655" target="_blank">9655</a> | <a href="https://www.acmicpc.net/problem/9655" target="_blank">돌 게임</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/6.svg"/>|
| 02  | <a href="https://www.acmicpc.net/problem/2407" target="_blank">2407</a> | <a href="https://www.acmicpc.net/problem/2407" target="_blank">조합</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/8.svg"/>|
| 03 | <a href="https://www.acmicpc.net/problem/11660" target="_blank">11660</a> | <a href="https://www.acmicpc.net/problem/11660" target="_blank">구간 합 구하기 5</a> |<img height="25px" width="25px" src="https://static.solved.ac/tier_small/10.svg"/> |
| 04 | <a href="https://www.acmicpc.net/problem/2293" target="_blank">2293</a> | <a href="https://www.acmicpc.net/problem/2293" target="_blank">동전 1</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/11.svg"/> |

**Comment by elizabethgim** [comment]
### 04.19.(수) : 봄버맨
- 가만두지 않아!!
![image](https://user-images.githubusercontent.com/65852282/232966763-9770eb11-0522-4fe4-8c72-e1641ec1bc24.png)

**Comment by elizabethgim** [comment]
### 04.19.(수)
- 너 두고 봐..
![image](https://user-images.githubusercontent.com/65852282/233048561-61971948-1e00-480e-b96d-219771355884.png)

**Comment by ParkJungYoon** [comment]
유진쓰 폭주한다..!?!!!!

**Comment by bedurgi999** [comment]
### 04.21.(금)
![image](https://user-images.githubusercontent.com/55628887/233609316-464f9062-b682-4b7e-b497-522047352f19.png)

**Comment by bedurgi999** [comment]
04.21.(금)
![image](https://user-images.githubusercontent.com/55628887/233609724-05412836-2517-47a1-b28b-41532e3c3d02.png)

**Comment by elizabethgim** [comment]
### 04.21.(금) : 조합
- 조합 오랜만이다..
![image](https://user-images.githubusercontent.com/65852282/233618128-f20d415e-0454-4c32-aad9-b8fbf97a2375.png)

**Comment by elizabethgim** [comment]
### 04.21.(금): 돌 게임
- 굳이굳이 DP로 풀어보기~
![image](https://user-images.githubusercontent.com/65852282/233620118-d3b3b1b5-b824-4e91-99db-6c594066b32f.png)

**Comment by ParkJungYoon** [comment]
마치... 시간초과를 위해 태어난 사람같아... 나도 다 풀었다 올리고 싶다..
왜 푸는 문제마다...

<img src="https://user-images.githubusercontent.com/97580782/233763270-cab105df-f6b1-47c8-96b9-ddcf14698edf.png" width="200px">
<img src="https://user-images.githubusercontent.com/97580782/233763293-95acc494-2450-4925-a134-db9d393ea4bd.png" width="200px">

**Comment by ParkJungYoon** [comment]
### 04.22 (토) : 돌 게임
상처만 남은 돌 게임

![스크린샷 2023-04-22 오후 4 57 17](https://user-images.githubusercontent.com/97580782/233771027-a6734308-59a3-4d74-8a94-2a13f64eacbb.png)

**Comment by ParkJungYoon** [comment]
### 04.22 (토) : 조합

분명 dp 문제집인데 그 무엇도 dp로 안풀고 있는 상황

![스크린샷 2023-04-22 오후 5 11 15](https://user-images.githubusercontent.com/97580782/233771869-5be84945-bdb0-4c72-ad31-bc7b08f21256.png)

**Comment by bedurgi999** [comment]
### 04.23.(일)

**Comment by ParkJungYoon** [comment]
### 04.23 (일) : 구간 합 구하기5

보선쓰 아 너무 많은데 하면서 다 풀어버리는 코딩 마스터

![스크린샷 2023-04-23 오후 3 01 04](https://user-images.githubusercontent.com/97580782/233822566-0ec3b937-d47e-4539-a6ee-1612523762a0.png)

**Comment by blcklamb** [comment]
### 04.25.(화): 조합
위 문제랑 동일한 풀이로 통과!
<img width="981" alt="image" src="https://user-images.githubusercontent.com/92101831/234066319-fdfc7b7f-b422-423c-b4e5-5bd4a308e45b.png">

**Comment by elizabethgim** [comment]
### 04.25.(화): 동전 1
점화식..어렵네요...극복한다...
![image](https://user-images.githubusercontent.com/65852282/234224440-8b6761bf-b2a2-45dd-b049-c74fff1eeb28.png)

**Comment by ParkJungYoon** [comment]
### 04.26 (수) : 동전 1

아니 dp 머선일입니까..? 역시 너무 싫어(?)

![스크린샷 2023-04-26 오후 1 10 25](https://user-images.githubusercontent.com/97580782/234467893-97cf908b-409a-4bcf-80e3-df7dd32cbc9f.png)

**Comment by blcklamb** [comment]
### 04.26.(수): 돌 게임
dp 문제가 아닌 것 같은디...
<img width="980" alt="image" src="https://user-images.githubusercontent.com/92101831/234551575-d6a942ce-057a-4192-aeda-82aac5b741f0.png">

**Comment by blcklamb** [comment]
### 04.26.(수): 구간 합 구하기5
못 풀고 스터디 참여할 것 같아요...
완전탐색으로 풀다가 야매 누적합으로 했는데도 시간 초과 떠요
<img width="968" alt="image" src="https://user-images.githubusercontent.com/92101831/234551745-6b6a3ba8-18ca-44be-ab29-5222d1919c51.png">

**Comment by ParkJungYoon** [comment]
## 라이브코딩

### 04.26(수)

11055 가장 큰 증가하는 부분 수열

**Comment by elizabethgim** [comment]
### 04.27(목) : 가장 큰 증가하는 부분 수열
- 이전에 풀었던 [가장 긴 증가하는 부분 수열](https://www.acmicpc.net/problem/11053) 참고 했다..감격..
![image](https://user-images.githubusercontent.com/65852282/234743465-d1b3aa3e-ff96-4ad7-85c2-79f321fe5d15.png)

**Comment by ParkJungYoon** [comment]
### 04.27(목) : 가장 큰 증가하는 부분 수열
와 이걸 생각한 사람은...천...천재야!!!!

![스크린샷 2023-04-27 오후 2 16 59](https://user-images.githubusercontent.com/97580782/234765833-652ba194-40f3-4fa6-8d15-408fe9a9bdff.png)
