### ISSUE TITLE
[23년 10월 4주차] 프로그래머스 문제풀이

### ISSUE THREAD

**Issue by blcklamb** [studying-ice-bear/pparkkkimeom#25]
## 🚀 스터디

- `일시`: 2023-10-26 (목) 20시 00분 ~ 21시 30분 (1.5h)
- `참석자`
  - [ ] 채정, 유진, 보선
- `내용`
   -  문제 설명
     -  어떤 문제를 설명할지는 랜덤으로 결정
   - 30분 동안 라이브 코테

### 🧩 과제

- 저번 주차 못푼 과제를 완료해주세요!
- 스터디 전까지 풀이한 뒤 커밋해주세요.
- 문제 풀이 결과를 댓글에 알려주세요!! 
  -  ex. 대단하다 나 자신. 이걸 풀어? 하... 인구 이동 문제 풀이 완!

|          순번          |        문제 이름         |         난이도          | 
| :-----: | :-----: | :-----: |
| 01  | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/138476" target="_blank">🍊귤 고르기</a> | Level 2 |
| 02  | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/160585" target="_blank">⭕️혼자서 하는 틱택토</a> | Level 2 |
| 03 | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/152995" target="_blank">🗂️인사고과</a> | Level 3 |
| 04 | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/159993" target="_blank">🎲미로탈출</a> | Level 2 |

**Comment by elizabethgim** [comment]
### 10.20.(금): 귤 고르기
- 자바 친구 어려워요...
![image](https://github.com/studying-ice-bear/pparkkkimeom/assets/65852282/08b9d633-e9ce-4f8f-b79d-cded8da83a64)

**Comment by elizabethgim** [comment]
### 10.25.(수): 혼자서 하는 틱택토
- 아니 이거 왤케 어려워요?
![image](https://github.com/studying-ice-bear/pparkkkimeom/assets/65852282/f1158b29-2eb8-407e-b0b1-b4525a3bea04)

**Comment by blcklamb** [comment]
### 10.26.(목): 귤 고르기
<img width="1150" alt="image" src="https://github.com/studying-ice-bear/pparkkkimeom/assets/92101831/3b67523b-4ea1-4c7d-b40e-134bfd2d0fb4">

```
'평균 시간: 106.861ms'
'평균 메모리: 72.332MB'
'최고 시간: 635ms'
'최저 시간: 0.07ms'
'최고 메모리: 193MB'
'최저 메모리: 33.4MB'
'시간 표준 편차: 198854.724'
'메모리 표준 편차: 23148.388'
```

**Comment by blcklamb** [comment]
### 10.26.(목): 미로 탈출
<img width="1056" alt="image" src="https://github.com/studying-ice-bear/pparkkkimeom/assets/92101831/99267897-a043-4e95-a0e2-0d1ad14c556a">

```
'평균 시간: 14.105ms'
'평균 메모리: 35.287MB'
'최고 시간: 58.3ms'
'최저 시간: 0.25ms'
'최고 메모리: 38.9MB'
'최저 메모리: 33.4MB'
'시간 표준 편차: 1754.747'
'메모리 표준 편차: 28.246'
```

**Comment by blcklamb** [comment]
### 10.26.(목): 혼자서 하는 틱택토
<img width="1102" alt="image" src="https://github.com/studying-ice-bear/pparkkkimeom/assets/92101831/59a70353-096b-4d24-ba31-f0284f6d9acb">

```
'평균 시간: 0.094ms'
'평균 메모리: 33.422MB'
'최고 시간: 0.15ms'
'최저 시간: 0.09ms'
'최고 메모리: 33.6MB'
'최저 메모리: 33.3MB'
'시간 표준 편차: 0.013'
'메모리 표준 편차: 4.579'
```

**Comment by blcklamb** [comment]
### 10.26.(목) 라이브코딩문제
###[🏨호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
