### ISSUE TITLE
[23년 11월 1주차] 프로그래머스 문제 풀이

### ISSUE THREAD

**Issue by blcklamb** [studying-ice-bear/pparkkkimeom#26]
## 🚀 스터디

- `일시`: 2023-11-02 (목) 21시 00분 ~ 22시 30분 (1.5h)
- `참석자`
  - [ ] 채정, 유진, 보선
- `내용`
   -  문제 설명
     -  어떤 문제를 설명할지는 랜덤으로 결정
   - 30분 동안 라이브 코테

### 🧩 과제

- 저번 주차 못푼 과제를 완료해주세요!
- 스터디 전까지 풀이한 뒤 커밋해주세요.
- 문제 풀이 결과를 댓글에 알려주세요!! 
  -  ex. 대단하다 나 자신. 이걸 풀어? 하... 인구 이동 문제 풀이 완!

|          순번          |        문제 이름         |         난이도          | 
| :-----: | :-----: | :-----: |
| 01  | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/155651" target="_blank">🏨호텔 대실</a> | Level 2 |
| 02  | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/172927" target="_blank">💎광물 캐기</a> | Level 2 |
| 03 | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/152995" target="_blank">🗂️인사고과</a> | Level 3 |
| 04 | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/131130" target="_blank">😎혼자 놀기의 달인</a> | Level 2 |

**Comment by elizabethgim** [comment]
### 11.09.(목)
SQL 쉽지 않아...
[즐겨찾기가 가장 많은 식당 정보 출력하기](https://school.programmers.co.kr/learn/courses/30/lessons/131123)
![image](https://github.com/studying-ice-bear/pparkkkimeom/assets/65852282/46e16066-150c-4c9d-9f68-4cc6fffcdd3f)
