### ISSUE TITLE
[23년 5월 1주차] 구현

### ISSUE THREAD

**Issue by ParkJungYoon** [studying-ice-bear/pparkkkimeom#3]
## 🚀 스터디

전설의 시작... 다시 돌아왔다.. 코딩몬스터

- `일시`: 2023-05-03 (수) 20시 ~ 21시 30분 (1.5h)
- `참석자`
  - [x] 유진, 정윤, 채정
  - 보선 개인 일정
- `내용`
   -  1시간 동안 문제 설명
     -  어떤 문제를 설명할지는 랜덤으로 결정
   - 30분 동안 라이브 코테

### 🧩 과제
- 저번 주차 못푼 과제를 완료해주세요!
- 스터디 전까지 풀이한 뒤 커밋해주세요.
- 문제 풀이 결과를 댓글에 알려주세요!! 
  -  ex. 대단하다 나 자신. 이걸 풀어? 하... 인구 이동 문제 풀이 완!

|          순번           |        문제 번호         |        문제 이름         |         난이도          | 
| :-----: | :-----: | :-----: | :-----: |
| 01  | <a href="https://www.acmicpc.net/problem/20546" target="_blank">20546</a> | <a href="https://www.acmicpc.net/problem/20546" target="_blank">🐜 기적의 매매법 🐜</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/6.svg"/> |
| 02  | <a href="https://www.acmicpc.net/problem/2578" target="_blank">2578</a> | <a href="https://www.acmicpc.net/problem/2578" target="_blank">빙고</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/7.svg"/> |
| 03 | <a href="https://www.acmicpc.net/problem/12933" target="_blank">12933</a> | <a href="https://www.acmicpc.net/problem/12933" target="_blank">오리</a> |<img height="25px" width="25px" src="https://static.solved.ac/tier_small/8.svg"/> |
| 04 | <a href="https://www.acmicpc.net/problem/21608" target="_blank">21608</a> | <a href="https://www.acmicpc.net/problem/21608" target="_blank">상어 초등학교</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/11.svg"/> |

**Comment by ParkJungYoon** [comment]
### 04.28 (금) : 기적의 매매법

![스크린샷 2023-04-28 오후 5 45 22](https://user-images.githubusercontent.com/97580782/235100482-911aa121-2a08-40dc-8065-b3e726a36d35.png)

**Comment by blcklamb** [comment]
### 04.28.(금): 기적의 매매법
주식은... 이렇게 하는 거 아니다...
<img width="985" alt="image" src="https://user-images.githubusercontent.com/92101831/235121232-4768a8e9-d9c0-4d8f-b82b-88d93c5e1f61.png">

**Comment by elizabethgim** [comment]
### 04.28(금): 빙고
- 넓게 생각하자
![image](https://user-images.githubusercontent.com/65852282/235153386-3e9cb032-691f-48e3-8d5a-2540049db5d0.png)

**Comment by elizabethgim** [comment]
### 04.28(금): 오리
- 꽥꽥
![image](https://user-images.githubusercontent.com/65852282/235153639-aff1f1a8-aca9-45a2-9130-60255454b698.png)

**Comment by blcklamb** [comment]
### 04.29.(토): 빙고
쉽게만 살아가면 재미없어 빙고
<img width="964" alt="image" src="https://user-images.githubusercontent.com/92101831/235189346-1c646180-076b-409a-8c53-ff78da250f8d.png">

**Comment by bedurgi999** [comment]
### 04.30.(일) : 기적의 매매법
![image](https://user-images.githubusercontent.com/55628887/235335581-52970685-3e91-436d-9feb-5eae7e747d85.png)

**Comment by bedurgi999** [comment]
### 04.30.(일) : 빙고
* 구현문제는 생각할게 너무 많다...
![image](https://user-images.githubusercontent.com/55628887/235337696-e2041859-371a-4eec-b2a8-771d27c4fd05.png)

**Comment by elizabethgim** [comment]
### 05.01.(월): 상어 초등학교
- 아기 상어..뚜루루뚜루..
![image](https://user-images.githubusercontent.com/65852282/235447352-5ea26e43-dac8-4a60-a0e3-dbc78f654179.png)

**Comment by bedurgi999** [comment]
### 05.02.(화) : 오리

![image](https://user-images.githubusercontent.com/55628887/235619212-09af9523-5b89-4749-b46d-60823ff34d81.png)

**Comment by blcklamb** [comment]
### 05.02.(화): 오리
🦆
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/92101831/235632485-faf16bc0-33ce-4a3c-894b-027fa0698b77.png">

**Comment by ParkJungYoon** [comment]
### 05.03(수): 오리

> 아뉘.. 내 머리 왜이러지... 굳었나..? ㅠㅠㅠ 안풀려서... 눈물흘리다가 답을 보고 말았어요..........

![스크린샷 2023-05-03 오후 2 13 37](https://user-images.githubusercontent.com/97580782/235836944-68da7f01-44ab-47b5-8135-2cf4d43f5f2c.png)

**Comment by blcklamb** [comment]
### 05.03.(수) 상어 초등학교

**Comment by blcklamb** [comment]
### 05.04.(목) 배열돌리기1
모각코 문제 [배열돌리기1](https://www.acmicpc.net/problem/16926)
<img width="994" alt="image" src="https://user-images.githubusercontent.com/92101831/235961483-1f15c878-3931-4f7a-a2a6-b02341ebdda7.png">
