### ISSUE TITLE
[23년 5월 2주차] 코딩테스트 고득점 Kit

### ISSUE THREAD

**Issue by ParkJungYoon** [studying-ice-bear/pparkkkimeom#4]
## 🚀 스터디

코테를 씹어먹기 위해 등장한 코딩 전사

- `일시`: 2023-05-10 (수) 20시 ~ 21시 30분 (1.5h)
- `참석자`
  - [x] 유진, 정윤, 보선, 채정
- `내용`
   -  1시간 동안 문제 설명
     -  어떤 문제를 설명할지는 랜덤으로 결정
   - 30분 동안 라이브 코테

### 🧩 과제
- 저번 주차 못푼 과제를 완료해주세요!
- 스터디 전까지 풀이한 뒤 커밋해주세요.
- 문제 풀이 결과를 댓글에 알려주세요!! 
  -  ex. 대단하다 나 자신. 이걸 풀어? 하... 인구 이동 문제 풀이 완!

|          순번           |        유형         |        문제 이름         |         난이도          | 
| :-----: | :-----: | :-----: | :-----: |
| 01  | <a href="https://school.programmers.co.kr/learn/courses/30/parts/12421" target="_blank">BFS/DFS</a> | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/43165" target="_blank">타겟 넘버</a> | Level 2 |
| 02  | <a href="https://school.programmers.co.kr/learn/courses/30/parts/12421" target="_blank">BFS/DFS</a> | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/1844" target="_blank">게임 맵 최단거리</a> | Level 2 |
| 03 | <a href="https://school.programmers.co.kr/learn/courses/30/parts/12081" target="_blank">스택/큐</a> | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/42583" target="_blank">다리를 지나는 트럭</a> | Level 2 |
| 04 | <a href="https://school.programmers.co.kr/learn/courses/30/parts/12230" target="_blank">완전탐색</a> | <a href="https://school.programmers.co.kr/learn/courses/30/lessons/42842" target="_blank">카펫</a> | Level 2 |

**Comment by blcklamb** [comment]
### 05.05.(금) 타겟 넘버, 게임 맵 최단거리
타겟 넘버는 이전에 푼 이력이 있어서 js로도 풀어봤습니다!
<img width="314" alt="image" src="https://user-images.githubusercontent.com/92101831/236408224-2f5f9bf7-533d-4cca-8e56-94a2ba373ab1.png">

**Comment by blcklamb** [comment]
### 05.09.(화) 다리를 지나는 트럭
뭔가 기출 너낌... 풀어본 기억이 있는데 어디서 풀어봤는지가 기억이 안 나요
<img width="431" alt="스크린샷 2023-05-09 오후 2 32 28" src="https://user-images.githubusercontent.com/92101831/237008714-6baa0e3c-a7fa-4043-b86a-fd015440f766.png">

<img width="468" alt="스크린샷 2023-05-09 오후 2 37 08" src="https://user-images.githubusercontent.com/92101831/237008743-d2870304-d6bb-4d61-a5e3-aea7702c09cd.png">


<img width="469" alt="image" src="https://user-images.githubusercontent.com/92101831/237008682-37fa3bfb-7cf0-49f5-858b-14dfd01dd5d4.png">

**Comment by blcklamb** [comment]
### 05.09.(화) 카펫
<img width="472" alt="스크린샷 2023-05-09 오후 3 07 26" src="https://user-images.githubusercontent.com/92101831/237008907-19334b2b-9028-4dcf-8287-742481836dca.png">

**Comment by elizabethgim** [comment]
### 05.10.(수) : 타겟 넘버
- 인증을 까먹었다!! 
![image](https://github.com/studying-ice-bear/pparkkkimeom/assets/65852282/5a2a99c7-6bb3-4ba6-903d-750e844196cc)

**Comment by elizabethgim** [comment]
### 05.10.(수): 카펫
- 왤케 이미지가 크게 들어가지
- 생각보다 복잡하지 않았던 문제, 쉽게 생각해보자. 그런데 설명이 더 구체적이었으면 좋았을 것 같다.
![image](https://github.com/studying-ice-bear/pparkkkimeom/assets/65852282/6b9cc3cb-9d0f-4130-9a64-8ad31868e653)

**Comment by elizabethgim** [comment]
### 5.10.(수) : 다리를 지나는 트럭
- 저번에 풀었던 [백준 문제](https://www.acmicpc.net/problem/13335)랑 유사하다.
- 그래도 기억 안나서 다시 풀어봄
![image](https://github.com/studying-ice-bear/pparkkkimeom/assets/65852282/a5edd90c-5e6a-48b7-8fd5-bf6d273c4f7b)

**Comment by bedurgi999** [comment]
### 05.10.(수) : 타겟 넘버
![image](https://github.com/studying-ice-bear/pparkkkimeom/assets/55628887/02f48536-874f-4018-b206-07632a4d89d9)

**Comment by elizabethgim** [comment]
### 05.10.(수): 게임 맵 최단 거리
- 왜 돼??
<img src="https://github.com/studying-ice-bear/pparkkkimeom/assets/65852282/25ae92c2-386a-410c-9579-4b3e34d3243e" width="50%" height="50%"/>

**Comment by elizabethgim** [comment]
결국 답을 봐버렸다...흑
![image](https://github.com/studying-ice-bear/pparkkkimeom/assets/65852282/44ac6b65-dd71-4020-b0a6-7ba8a716ce28)
